### ISSUE TITLE
Help. DDwar

### ISSUE THREAD

**Issue by HachikoS** [eeeee/teeworlds#17]
Hello. I can not do your ddwar. After all, no server inside. Help!

**Comment by eeeee** [comment]
Oh noes! I'm sorry you have some problem with ddwar but it is unlikely to be ddwar issue. 

However you are always welcome to join the IRC channel #ddwar on Quakenet for server compilation and configuration support. Maybe with our help you'd be able to do some ddwar and even get a server inside.

**Comment by HachikoS** [comment]
site plz

**Comment by fstd** [comment]
server: irc.quakenet.org, port: 6667 channel: #ddwar
